/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CategoryBreakdown {
  'count' : bigint,
  'totalSpent' : number,
  'category' : string,
}
export interface DashboardStats {
  'pendingCount' : bigint,
  'cancelledCount' : bigint,
  'totalOrders' : bigint,
  'totalSpent' : number,
  'recentOrders' : Array<Product>,
  'replacedCount' : bigint,
  'receivedCount' : bigint,
}
export interface MonthlySpend {
  'month' : string,
  'orderCount' : bigint,
  'totalSpent' : number,
}
export interface Product {
  'id' : string,
  'status' : string,
  'paymentMethod' : string,
  'purchasePrice' : number,
  'finalAmount' : number,
  'purchaseDate' : bigint,
  'ownerId' : string,
  'createdAt' : bigint,
  'trackingId' : string,
  'deliveryDate' : bigint,
  'courierName' : string,
  'description' : string,
  'productName' : string,
  'orderId' : string,
  'updatedAt' : bigint,
  'invoiceNumber' : string,
  'currency' : string,
  'address' : string,
  'notes' : string,
  'warrantyExpiry' : bigint,
  'discount' : number,
  'category' : string,
  'imageId' : string,
  'platformLink' : string,
  'platformName' : string,
}
export interface ProductFilter {
  'categoryFilter' : string,
  'sortBy' : string,
  'sortDesc' : boolean,
  'page' : bigint,
  'pageSize' : bigint,
  'search' : string,
  'maxPrice' : number,
  'toDate' : bigint,
  'fromDate' : bigint,
  'minPrice' : number,
  'statusFilter' : string,
}
export interface ProductInput {
  'status' : string,
  'paymentMethod' : string,
  'purchasePrice' : number,
  'purchaseDate' : bigint,
  'trackingId' : string,
  'deliveryDate' : bigint,
  'courierName' : string,
  'description' : string,
  'productName' : string,
  'orderId' : string,
  'invoiceNumber' : string,
  'currency' : string,
  'address' : string,
  'notes' : string,
  'warrantyExpiry' : bigint,
  'discount' : number,
  'category' : string,
  'imageId' : string,
  'platformLink' : string,
  'platformName' : string,
}
export interface ProductPage {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<Product>,
}
export interface StatusDistribution { 'status' : string, 'count' : bigint }
export interface UserProfile {
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[ProductInput], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[string], boolean>,
  'deleteProducts' : ActorMethod<[Array<string>], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryBreakdown' : ActorMethod<[], Array<CategoryBreakdown>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMonthlySpend' : ActorMethod<[], Array<MonthlySpend>>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getProducts' : ActorMethod<[ProductFilter], ProductPage>,
  'getStatusDistribution' : ActorMethod<[], Array<StatusDistribution>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProduct' : ActorMethod<[string, ProductInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];