/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductInput = IDL.Record({
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'purchasePrice' : IDL.Float64,
  'purchaseDate' : IDL.Int,
  'trackingId' : IDL.Text,
  'deliveryDate' : IDL.Int,
  'courierName' : IDL.Text,
  'description' : IDL.Text,
  'productName' : IDL.Text,
  'orderId' : IDL.Text,
  'invoiceNumber' : IDL.Text,
  'currency' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'warrantyExpiry' : IDL.Int,
  'discount' : IDL.Float64,
  'category' : IDL.Text,
  'imageId' : IDL.Text,
  'platformLink' : IDL.Text,
  'platformName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
});
export const CategoryBreakdown = IDL.Record({
  'count' : IDL.Nat,
  'totalSpent' : IDL.Float64,
  'category' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'purchasePrice' : IDL.Float64,
  'finalAmount' : IDL.Float64,
  'purchaseDate' : IDL.Int,
  'ownerId' : IDL.Text,
  'createdAt' : IDL.Int,
  'trackingId' : IDL.Text,
  'deliveryDate' : IDL.Int,
  'courierName' : IDL.Text,
  'description' : IDL.Text,
  'productName' : IDL.Text,
  'orderId' : IDL.Text,
  'updatedAt' : IDL.Int,
  'invoiceNumber' : IDL.Text,
  'currency' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'warrantyExpiry' : IDL.Int,
  'discount' : IDL.Float64,
  'category' : IDL.Text,
  'imageId' : IDL.Text,
  'platformLink' : IDL.Text,
  'platformName' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'pendingCount' : IDL.Nat,
  'cancelledCount' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'totalSpent' : IDL.Float64,
  'recentOrders' : IDL.Vec(Product),
  'replacedCount' : IDL.Nat,
  'receivedCount' : IDL.Nat,
});
export const MonthlySpend = IDL.Record({
  'month' : IDL.Text,
  'orderCount' : IDL.Nat,
  'totalSpent' : IDL.Float64,
});
export const ProductFilter = IDL.Record({
  'categoryFilter' : IDL.Text,
  'sortBy' : IDL.Text,
  'sortDesc' : IDL.Bool,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'search' : IDL.Text,
  'maxPrice' : IDL.Float64,
  'toDate' : IDL.Int,
  'fromDate' : IDL.Int,
  'minPrice' : IDL.Float64,
  'statusFilter' : IDL.Text,
});
export const ProductPage = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(Product),
});
export const StatusDistribution = IDL.Record({
  'status' : IDL.Text,
  'count' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([ProductInput], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteProducts' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryBreakdown' : IDL.Func(
      [],
      [IDL.Vec(CategoryBreakdown)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMonthlySpend' : IDL.Func([], [IDL.Vec(MonthlySpend)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([ProductFilter], [ProductPage], ['query']),
  'getStatusDistribution' : IDL.Func(
      [],
      [IDL.Vec(StatusDistribution)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProduct' : IDL.Func([IDL.Text, ProductInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductInput = IDL.Record({
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'purchasePrice' : IDL.Float64,
    'purchaseDate' : IDL.Int,
    'trackingId' : IDL.Text,
    'deliveryDate' : IDL.Int,
    'courierName' : IDL.Text,
    'description' : IDL.Text,
    'productName' : IDL.Text,
    'orderId' : IDL.Text,
    'invoiceNumber' : IDL.Text,
    'currency' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'warrantyExpiry' : IDL.Int,
    'discount' : IDL.Float64,
    'category' : IDL.Text,
    'imageId' : IDL.Text,
    'platformLink' : IDL.Text,
    'platformName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
  });
  const CategoryBreakdown = IDL.Record({
    'count' : IDL.Nat,
    'totalSpent' : IDL.Float64,
    'category' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'purchasePrice' : IDL.Float64,
    'finalAmount' : IDL.Float64,
    'purchaseDate' : IDL.Int,
    'ownerId' : IDL.Text,
    'createdAt' : IDL.Int,
    'trackingId' : IDL.Text,
    'deliveryDate' : IDL.Int,
    'courierName' : IDL.Text,
    'description' : IDL.Text,
    'productName' : IDL.Text,
    'orderId' : IDL.Text,
    'updatedAt' : IDL.Int,
    'invoiceNumber' : IDL.Text,
    'currency' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'warrantyExpiry' : IDL.Int,
    'discount' : IDL.Float64,
    'category' : IDL.Text,
    'imageId' : IDL.Text,
    'platformLink' : IDL.Text,
    'platformName' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'pendingCount' : IDL.Nat,
    'cancelledCount' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'totalSpent' : IDL.Float64,
    'recentOrders' : IDL.Vec(Product),
    'replacedCount' : IDL.Nat,
    'receivedCount' : IDL.Nat,
  });
  const MonthlySpend = IDL.Record({
    'month' : IDL.Text,
    'orderCount' : IDL.Nat,
    'totalSpent' : IDL.Float64,
  });
  const ProductFilter = IDL.Record({
    'categoryFilter' : IDL.Text,
    'sortBy' : IDL.Text,
    'sortDesc' : IDL.Bool,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'search' : IDL.Text,
    'maxPrice' : IDL.Float64,
    'toDate' : IDL.Int,
    'fromDate' : IDL.Int,
    'minPrice' : IDL.Float64,
    'statusFilter' : IDL.Text,
  });
  const ProductPage = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(Product),
  });
  const StatusDistribution = IDL.Record({
    'status' : IDL.Text,
    'count' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([ProductInput], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteProducts' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryBreakdown' : IDL.Func(
        [],
        [IDL.Vec(CategoryBreakdown)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMonthlySpend' : IDL.Func([], [IDL.Vec(MonthlySpend)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([ProductFilter], [ProductPage], ['query']),
    'getStatusDistribution' : IDL.Func(
        [],
        [IDL.Vec(StatusDistribution)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProduct' : IDL.Func([IDL.Text, ProductInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };